image: node:lts

cache:
  paths:
    - node_modules/

before_script:
  # Gitlab Token
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc
  # Ignore root permission
  - npm config set user 0 && npm config set unsafe-perm true
  # Update apt-get Sources
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
  - echo "deb http://http.debian.net/debian jessie-backports main" | tee --append /etc/apt/sources.list.d/jessie-backports.list > /dev/null
  - apt-get update && apt-get upgrade -qq -y
  # Install Chrome
  - apt-get install google-chrome-stable -qq -y && mv /usr/bin/google-chrome /usr/bin/google-chrome-orig && echo '#!/bin/bash' > /usr/bin/google-chrome && echo '/usr/bin/google-chrome-orig --no-sandbox --disable-setuid-sandbox --allow-sandbox-debugging "$@"' >> /usr/bin/google-chrome && chmod +x /usr/bin/google-chrome
  # Install dependencies
  - npm i

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - npm run lint
  tags:
    - docker

test:
  stage: test
  script:
    - npm test
  tags:
    - docker
